### ISSUE TITLE
Incremental Updates

### ISSUE THREAD

**Issue by dusx1981** [XGenerationLab/M-Schema#2]
Hi，I am working on the nl2sql project, and the design of MShema solves some important problems for me. It would be very helpful if incremental updates could be achieved.

**Comment by XGenerationLab** [comment]
Thank you for your feedback! Could you please clarify what you mean by "incremental updates"?

**Comment by dusx1981** [comment]
> Thank you for your feedback! Could you please clarify what you mean by "incremental updates"?

在我做这些操作时，MSchema 的数据可以增量更新：
1：增加表，删除表
2：增加列，删除列
3：修改表，修改列

**Comment by XGenerationLab** [comment]
M-SChema的获取是一个异步的过程，暂时不支持同步数据库，你可以在每次修改之后重新初始化M-Schema。
