### ISSUE TITLE
缓存管理

### ISSUE THREAD

**Issue by dusx1981** [XGenerationLab/M-Schema#3]
我看到表格的内容，是被放到内存里的，如果数据库的表非常多，宽表也非常多，需不需要考虑 内存的管理问题，比如上千个表，都是宽表。

**Comment by XGenerationLab** [comment]
是的，我们只是一个简单的算法实现，M-Schema本身存储的数据并不多，在大多数情况下是可行的；当表的数量特别多，比如数十万张表，就需要考虑内存管理的问题，在工程上还有很多优化的空间。
